Repository ArchiveTeam/ArchiveBot, pull requests merged in 2019-05, with the labels that each got.

#360 Add some error handling
  dashboard/resources/recent.rb
  plumbing/analyze-logs
  plumbing/log-firehose
Labels: backend

#355 Add pending-ao counter to !status reply
  bot/summary.rb
  doc/commands.rst
Labels: enhancement, irc

#356 Add alias --concurrent for !a/!ao command and !concurrent for !concurrency
  bot/command_patterns.rb
  bot/job_options_parser.rb
  doc/commands.rst
Labels: enhancement, irc

#357 Allow unauthorised users to add an explanation to their own jobs (fixes #223)
  bot/brain.rb
Labels: enhancement, irc

#363 Add pending job list to the dashboard and disable !pending when the queue is long
  bot/brain.rb
  dashboard/app.rb
  dashboard/resources/pending.rb
Labels: backend, enhancement, irc

#364 Add Edge UA
  db/user_agents/edge.json
Labels: enhancement

#367 New dashboard WebSocket server
  INSTALL.backend
  dashboard/app.rb
  dashboard/assets/scripts/Dashboard.hx
  dashboard/assets/scripts/dashboard.js
  dashboard/dashboard.html
  dashboard/dashboard3.html
  dashboard/log_actors.rb
  dashboard/websocket.py
  test/run_dashboard.sh
Labels: backend, enhancement

#365 Update Safari UA
  db/user_agents/safari.json
Labels: enhancement, useragents

#366 Add macOS Chrome UA
  db/user_agents/chrome.json
Labels: enhancement, useragents

#369 Various improvements for MediaWiki ignores
  db/ignore_patterns/mediawiki.json
  db/ignore_patterns/nomediawikihistory.json
Labels: enhancement, ignores

#370 Ignore Squarespace JS hell
  db/ignore_patterns/global.json
Labels: enhancement, ignores

#371 A few blogs igset improvements
  db/ignore_patterns/blogs.json
Labels: enhancement, ignores

#372 Basic Mastodon igset
  db/ignore_patterns/mastodon.json
Labels: enhancement, ignores

#373 Add igsets for GitHub
  db/ignore_patterns/github.json
  db/ignore_patterns/nogithubcode.json
Labels: enhancement, ignores

#374 Add separate igsets for MediaWiki locales and a script to generate them from MW message files
  db/ignore_patterns/mediawiki-de.json
  db/ignore_patterns/mediawiki-es.json
  db/ignore_patterns/mediawiki-fr.json
  db/ignore_patterns/mediawiki-lang.py
  db/ignore_patterns/mediawiki-ru.json
  db/ignore_patterns/mediawiki.json
Labels: enhancement, ignores

#376 Update user agents to current versions
  db/user_agents/chrome.json
  db/user_agents/edge.json
  db/user_agents/firefox.json
  db/user_agents/safari.json
Labels: enhancement, useragents

#377 Self-host the dashboard's JS dependencies and update them
  dashboard/app.rb
  dashboard/assets/images/sort_asc.png
  dashboard/assets/images/sort_asc_disabled.png
  dashboard/assets/images/sort_both.png
  dashboard/assets/images/sort_desc.png
  dashboard/assets/images/sort_desc_disabled.png
  dashboard/assets/scripts/jquery-3.4.1.min.js
  dashboard/assets/scripts/jquery.dataTables.min.js
  dashboard/assets/stylesheets/jquery.dataTables.min.css
  dashboard/pipeline.html
  dashboard/recent.html
Labels: dashboard, enhancement
